### ISSUE TITLE
홈 화면 이벤트 추가

### ISSUE THREAD

**Issue by poytok** [f-lab-edu/DeliveryService#14]
# Description
홈 화면 이벤트 추가하기

## Todo
- [x] 클릭 시 상세화면 보여주기 
- [x] 상세화면 택배 리스트 추가하기
- [x] 상세 화면 인터랙션 추가하기
- [x] 날짜 변경 기능 추가하기
