### ISSUE TITLE
버그 수정 및 기능 추가

### ISSUE THREAD

**Issue by poytok** [f-lab-edu/DeliveryService#23]
# Description
기능에 대한 버그 수정과 추가적인 기능

## Todo
- [x] 홈 dot 날짜 이상 버그 수정
- [x] 홈 제스쳐 인터랙션 추가
- [x] API 호출 시간 Firebase로 관리하기
- [x] data store 위임 패턴으로 변경하기

## Etc
홈 뷰페이저 추가
